bebops:
  bebop_one:
    ros_master_port: '11311'
    gazebo_port: '11321'
    initial_position: [0.0, 0.0, 1.5, 0.0]
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.applications.parrot.tumsim.rats.TumSimCollisionExperiment
      nodename: BeSwarmOne
      rosparam:
        unique_integer_id: 1
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0
        initial_pos_x: 0.0
        initial_pos_y: 0.0
        initial_pos_z: 1.5
        initial_pos_yaw: 0.0
        final_pos_x: 10.0
        final_pos_y: 0.0
        final_pos_z: 1.5
        final_pos_yaw: 0.0
        velocity: 1.0
        localization_deviation: 0.5

  bebop_two:
    ros_master_port: '11312'
    gazebo_port: '11322'
    initial_position: [10.0, 0.5, 1.5, 0.0]
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.applications.parrot.tumsim.rats.TumSimCollisionExperiment
      nodename: BeSwarmTwo
      rosparam:
        unique_integer_id: 2
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0
        initial_pos_x: 10.0
        initial_pos_y: 0.5
        initial_pos_z: 1.5
        initial_pos_yaw: 0.0
        final_pos_x: 0.0
        final_pos_y: 0.5
        final_pos_z: 1.5
        final_pos_yaw: 0.0
        velocity: 1.0
        localization_deviation: 0.5

synchronizer:
  ros_master_port: '11313'
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}