bebops:
  bebop_one:
    ros_master_port: '11311'
    gazebo_port: '11321'
    master_sync_config_file: ${abs_path}/master_sync.yaml
    initial_position: [1.0, -1, 1.5, 0.0]
    beswarm_config:
      beswarm_config_file: ${abs_path}/beswarm.yaml
      javanode: applications.parrot.tumsim.rats.TumSimOneCircle
      nodename: BeSwarmOne
      rosparam:
        drone_name: drone_one
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  bebop_two:
    ros_master_port: '11312'
    gazebo_port: '11322'
    master_sync_config_file: ${abs_path}/master_sync.yaml
    initial_position: [1.0, -3, 1.5, 0.0]
    beswarm_config:
      beswarm_config_file: ${abs_path}/beswarm.yaml
      javanode: applications.parrot.tumsim.rats.TumSimTwoCircle
      nodename: BeSwarmTwo
      rosparam:
        drone_name: drone_two
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

synchronizer:
  ros_master_port: '11313'
  master_sync_config_file: ${abs_path}/master_sync.yaml
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}