bebops:
  bebop_one:
    ros_master_port: '11311'
    gazebo_port: '11321'
    initial_position: [1.0, -1, 1.5, 0.0]
    beswarm_config:
      javanode: io.github.hoangtungdinh.applications.parrot.tumsim.rats.TumSimOneCircle
      nodename: BeSwarmOne
      rosparam:
        unique_integer_id: 1
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  bebop_two:
    ros_master_port: '11312'
    gazebo_port: '11322'
    initial_position: [1.0, -3, 1.5, 0.0]
    beswarm_config:
      javanode: io.github.hoangtungdinh.applications.parrot.tumsim.rats.TumSimTwoCircle
      nodename: BeSwarmTwo
      rosparam:
        unique_integer_id: 2
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

synchronizer:
  ros_master_port: '11313'
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}