bebops:
  bebop_one:
    ros_master_port: '11311'
    gazebo_port: '11321'
    initial_position: [3.0,1.0,1.5,-3.14]
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.applications.parrot.tumsim.rats.TumSimGeofenceExperiment
      nodename: BeSwarmOne
      rosparam:
        unique_integer_id: 1
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0
        start_pose: '[3.0,1.0,1.5,-3.14]'
        end_pose: '[3.0,-3.0,1.5,-3.14]'
        velocity: 1.0
        localization_deviation: 0.0
        max_acceleration: '[3.0,3.0,3.0]'

synchronizer:
  ros_master_port: '11313'
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}