bebops:
  Fievel:
    ros_master_port: '11312'
    gazebo_port: '11322'
    initial_position: [6.0, 3.0, 1.0, -1.57]
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.applications.parrot.tumsim.rats.swarmviewcircle.FievelCircle
      nodename: BeSwarmFievel
      rosparam:
        unique_integer_id: 2
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  Juliet:
    ros_master_port: '11313'
    gazebo_port: '11323'
    initial_position: [4.0, 5.0, 1.0, -1.57]
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.applications.parrot.tumsim.rats.swarmviewcircle.JulietCircle
      nodename: BeSwarmJuliet
      rosparam:
        unique_integer_id: 3
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  Nerve:
    ros_master_port: '11314'
    gazebo_port: '11324'
    initial_position: [4.0, 1.0, 1.0, -1.57]
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.applications.parrot.tumsim.rats.swarmviewcircle.NerveCircle
      nodename: BeSwarmNerve
      rosparam:
        unique_integer_id: 4
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  Romeo:
    ros_master_port: '11315'
    gazebo_port: '11325'
    initial_position: [2.0, 3.0, 1.0, -1.57]
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.applications.parrot.tumsim.rats.swarmviewcircle.RomeoCircle
      nodename: BeSwarmRomeo
      rosparam:
        unique_integer_id: 5
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

synchronizer:
  ros_master_port: '11316'
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}