bebops:
  Dumbo:
    ros_master_port: '11311'
    gazebo_port: '11321'
    initial_position: [7.0, 3.0, 1.0]
    beswarm_config:
      javanode: applications.parrot.tumsim.rats.swarmview.DumboSwarmView
      nodename: BeSwarmOne
      rosparam:
        unique_integer_id: 1
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  Fievel:
    ros_master_port: '11312'
    gazebo_port: '11322'
    initial_position: [1.0, 6.0, 1.0]
    beswarm_config:
      javanode: applications.parrot.tumsim.rats.swarmview.FievelSwarmView
      nodename: BeSwarmTwo
      rosparam:
        unique_integer_id: 2
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  Juliet:
    ros_master_port: '11313'
    gazebo_port: '11323'
    initial_position: [1.0, 5.0, 1.0]
    beswarm_config:
      javanode: applications.parrot.tumsim.rats.swarmview.JulietSwarmView
      nodename: BeSwarmTwo
      rosparam:
        unique_integer_id: 3
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  Nerve:
    ros_master_port: '11314'
    gazebo_port: '11324'
    initial_position: [7.0, 6.0, 1.0]
    beswarm_config:
      javanode: applications.parrot.tumsim.rats.swarmview.NerveSwarmView
      nodename: BeSwarmTwo
      rosparam:
        unique_integer_id: 4
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0


  Romeo:
    ros_master_port: '11315'
    gazebo_port: '11325'
    initial_position: [7.0, 5.0, 1.0]
    beswarm_config:
      javanode: applications.parrot.tumsim.rats.swarmview.RomeoSwarmView
      nodename: BeSwarmTwo
      rosparam:
        unique_integer_id: 5
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

synchronizer:
  ros_master_port: '11316'
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}